name: YAML Analyzer

on:
  push:
  pull_request:
  workflow_dispatch: # Allows the workflow to be manually triggered

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv env
          .\env\Scripts\activate.bat
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Generate HTML report
        if: always()
        run: |
          mkdir report
          pytest --html=report\report-$(Get-Date -Format "yyyyMMdd-HHmmss").html

      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: report/
